#!/usr/bin/env python3
"""Replace Appendix D block in the main report with the freshly generated one.

The script is idempotent: it searches for the generator annotation marker and
the end-of-appendix footer (either `_총 N개 함수 항목._` from the legacy output
or `_총 N개 DAX 함수 색인...` from the new layout) and replaces everything in
between with the contents of `report/_generated_dax_appendix.md`.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "report" / "20260420_power_bi_report.md"
APPX = ROOT / "report" / "_generated_dax_appendix.md"

START_MARKER = (
    "<!-- annotation: DAX appendix generated by scripts/"
    "generate_power_bi_dax_m_appendices.py -->"
)
# Either the legacy footer or the new one
FOOTER_PATTERN = re.compile(
    r"_총 \d+개 (?:함수 항목|DAX 함수 색인[^\n]*)\._"
)


def main() -> int:
    content = REPORT.read_text(encoding="utf-8")
    new_appx = APPX.read_text(encoding="utf-8").rstrip() + "\n"

    start = content.find(START_MARKER)
    if start < 0:
        raise SystemExit("start marker not found; appendix D block missing")
    match = FOOTER_PATTERN.search(content, start)
    if not match:
        raise SystemExit("appendix D footer not found")
    end = match.end()

    before = content[:start]
    after = content[end:]
    if after.startswith("\n"):
        after = after  # keep blank line as-is
    merged = before + new_appx + after
    REPORT.write_text(merged, encoding="utf-8")
    print(
        "patched: replaced",
        f"{end - start:,}",
        "chars with",
        f"{len(new_appx):,}",
        "chars",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
